evidence(e_ksea(e1, s10, dec)).
evidence(e_ksea(e1, s2, inc)).
evidence(e_ksea(e1, s22, dec)).
evidence(e_ksea(e1, s23, inc)).
evidence(e_ksea(e1, s40, dec)).
evidence(e_ksea(e1, s61, inc)).
evidence(e_ksea(e1, s62, dec)).
evidence(e_ksea(e1, s63, inc)).
evidence(e_ksea(e1, s7, dec)).
evidence(e_ksea(e1, s99, inc)).
evidence(e_ksea(e2, s10, inc)).
evidence(e_ksea(e2, s2, dec)).
evidence(e_ksea(e2, s22, dec)).
evidence(e_ksea(e2, s23, inc)).
evidence(e_ksea(e2, s40, dec)).
evidence(e_ksea(e2, s61, dec)).
evidence(e_ksea(e2, s62, inc)).
evidence(e_ksea(e2, s63, dec)).
evidence(e_ksea(e2, s7, dec)).
evidence(e_ksea(e2, s99, dec)).
evidence(e_ksea(e3, s10, inc)).
evidence(e_ksea(e3, s2, dec)).
evidence(e_ksea(e3, s22, inc)).
evidence(e_ksea(e3, s23, dec)).
evidence(e_ksea(e3, s40, dec)).
evidence(e_ksea(e3, s61, dec)).
evidence(e_ksea(e3, s62, dec)).
evidence(e_ksea(e3, s63, inc)).
evidence(e_ksea(e3, s7, inc)).
evidence(e_ksea(e3, s99, inc)).
evidence(p_fc(p0, s10, dec)).
evidence(p_fc(p0, s2, inc)).
evidence(p_fc(p0, s22, dec)).
evidence(p_fc(p0, s23, inc)).
evidence(p_fc(p0, s40, dec)).
evidence(p_fc(p0, s61, inc)).
evidence(p_fc(p0, s62, inc)).
evidence(p_fc(p0, s63, dec)).
evidence(p_fc(p0, s7, dec)).
evidence(p_fc(p0, s99, inc)).
