evidence(e_activity(e1, s1, inc)).
evidence(e_activity(e1, s10, dec)).
evidence(e_activity(e1, s11, base)).
evidence(e_activity(e1, s12, dec)).
evidence(e_activity(e1, s14, base)).
evidence(e_activity(e1, s15, dec)).
evidence(e_activity(e1, s16, base)).
evidence(e_activity(e1, s17, base)).
evidence(e_activity(e1, s19, dec)).
evidence(e_activity(e1, s2, inc)).
evidence(e_activity(e1, s20, dec)).
evidence(e_activity(e1, s21, dec)).
evidence(e_activity(e1, s22, base)).
evidence(e_activity(e1, s23, inc)).
evidence(e_activity(e1, s25, inc)).
evidence(e_activity(e1, s27, inc)).
evidence(e_activity(e1, s28, inc)).
evidence(e_activity(e1, s29, inc)).
evidence(e_activity(e1, s3, dec)).
evidence(e_activity(e1, s30, inc)).
evidence(e_activity(e1, s32, inc)).
evidence(e_activity(e1, s34, inc)).
evidence(e_activity(e1, s36, inc)).
evidence(e_activity(e1, s37, inc)).
evidence(e_activity(e1, s38, dec)).
evidence(e_activity(e1, s39, dec)).
evidence(e_activity(e1, s4, base)).
evidence(e_activity(e1, s40, base)).
evidence(e_activity(e1, s41, inc)).
evidence(e_activity(e1, s42, dec)).
evidence(e_activity(e1, s43, inc)).
evidence(e_activity(e1, s45, inc)).
evidence(e_activity(e1, s47, base)).
evidence(e_activity(e1, s48, base)).
evidence(e_activity(e1, s49, dec)).
evidence(e_activity(e1, s5, inc)).
evidence(e_activity(e1, s50, dec)).
evidence(e_activity(e1, s52, dec)).
evidence(e_activity(e1, s53, inc)).
evidence(e_activity(e1, s54, base)).
evidence(e_activity(e1, s56, inc)).
evidence(e_activity(e1, s57, base)).
evidence(e_activity(e1, s58, dec)).
evidence(e_activity(e1, s59, inc)).
evidence(e_activity(e1, s6, base)).
evidence(e_activity(e1, s61, inc)).
evidence(e_activity(e1, s62, base)).
evidence(e_activity(e1, s63, inc)).
evidence(e_activity(e1, s64, inc)).
evidence(e_activity(e1, s66, inc)).
evidence(e_activity(e1, s67, inc)).
evidence(e_activity(e1, s68, dec)).
evidence(e_activity(e1, s69, base)).
evidence(e_activity(e1, s7, base)).
evidence(e_activity(e1, s70, inc)).
evidence(e_activity(e1, s71, inc)).
evidence(e_activity(e1, s72, dec)).
evidence(e_activity(e1, s74, inc)).
evidence(e_activity(e1, s75, inc)).
evidence(e_activity(e1, s76, dec)).
evidence(e_activity(e1, s77, inc)).
evidence(e_activity(e1, s8, inc)).
evidence(e_activity(e1, s80, base)).
evidence(e_activity(e1, s81, inc)).
evidence(e_activity(e1, s82, inc)).
evidence(e_activity(e1, s83, dec)).
evidence(e_activity(e1, s84, dec)).
evidence(e_activity(e1, s85, base)).
evidence(e_activity(e1, s86, inc)).
evidence(e_activity(e1, s87, dec)).
evidence(e_activity(e1, s88, dec)).
evidence(e_activity(e1, s89, inc)).
evidence(e_activity(e1, s90, inc)).
evidence(e_activity(e1, s91, inc)).
evidence(e_activity(e1, s92, dec)).
evidence(e_activity(e1, s93, dec)).
evidence(e_activity(e1, s94, dec)).
evidence(e_activity(e1, s96, base)).
evidence(e_activity(e1, s97, dec)).
evidence(e_activity(e1, s99, inc)).
evidence(e_activity(e2, s1, dec)).
evidence(e_activity(e2, s10, inc)).
evidence(e_activity(e2, s11, base)).
evidence(e_activity(e2, s12, base)).
evidence(e_activity(e2, s14, inc)).
evidence(e_activity(e2, s15, inc)).
evidence(e_activity(e2, s16, base)).
evidence(e_activity(e2, s17, dec)).
evidence(e_activity(e2, s19, base)).
evidence(e_activity(e2, s2, dec)).
evidence(e_activity(e2, s20, inc)).
evidence(e_activity(e2, s21, inc)).
evidence(e_activity(e2, s22, dec)).
evidence(e_activity(e2, s23, base)).
evidence(e_activity(e2, s25, dec)).
evidence(e_activity(e2, s27, dec)).
evidence(e_activity(e2, s28, dec)).
evidence(e_activity(e2, s29, dec)).
evidence(e_activity(e2, s3, dec)).
evidence(e_activity(e2, s30, dec)).
evidence(e_activity(e2, s32, inc)).
evidence(e_activity(e2, s34, base)).
evidence(e_activity(e2, s36, base)).
evidence(e_activity(e2, s37, inc)).
evidence(e_activity(e2, s38, base)).
evidence(e_activity(e2, s39, base)).
evidence(e_activity(e2, s4, inc)).
evidence(e_activity(e2, s40, dec)).
evidence(e_activity(e2, s41, inc)).
evidence(e_activity(e2, s42, base)).
evidence(e_activity(e2, s43, dec)).
evidence(e_activity(e2, s45, inc)).
evidence(e_activity(e2, s47, base)).
evidence(e_activity(e2, s48, inc)).
evidence(e_activity(e2, s49, base)).
evidence(e_activity(e2, s5, base)).
evidence(e_activity(e2, s50, inc)).
evidence(e_activity(e2, s52, dec)).
evidence(e_activity(e2, s53, dec)).
evidence(e_activity(e2, s54, dec)).
evidence(e_activity(e2, s56, dec)).
evidence(e_activity(e2, s57, dec)).
evidence(e_activity(e2, s58, base)).
evidence(e_activity(e2, s59, dec)).
evidence(e_activity(e2, s6, inc)).
evidence(e_activity(e2, s61, dec)).
evidence(e_activity(e2, s62, inc)).
evidence(e_activity(e2, s63, base)).
evidence(e_activity(e2, s64, inc)).
evidence(e_activity(e2, s66, dec)).
evidence(e_activity(e2, s67, base)).
evidence(e_activity(e2, s68, inc)).
evidence(e_activity(e2, s69, inc)).
evidence(e_activity(e2, s7, dec)).
evidence(e_activity(e2, s70, base)).
evidence(e_activity(e2, s71, inc)).
evidence(e_activity(e2, s72, dec)).
evidence(e_activity(e2, s74, inc)).
evidence(e_activity(e2, s75, inc)).
evidence(e_activity(e2, s76, dec)).
evidence(e_activity(e2, s77, inc)).
evidence(e_activity(e2, s8, dec)).
evidence(e_activity(e2, s80, dec)).
evidence(e_activity(e2, s81, inc)).
evidence(e_activity(e2, s82, base)).
evidence(e_activity(e2, s83, dec)).
evidence(e_activity(e2, s84, base)).
evidence(e_activity(e2, s85, dec)).
evidence(e_activity(e2, s86, inc)).
evidence(e_activity(e2, s87, base)).
evidence(e_activity(e2, s88, inc)).
evidence(e_activity(e2, s89, base)).
evidence(e_activity(e2, s90, base)).
evidence(e_activity(e2, s91, dec)).
evidence(e_activity(e2, s92, base)).
evidence(e_activity(e2, s93, base)).
evidence(e_activity(e2, s94, inc)).
evidence(e_activity(e2, s96, dec)).
evidence(e_activity(e2, s97, dec)).
evidence(e_activity(e2, s99, base)).
evidence(e_activity(e3, s1, inc)).
evidence(e_activity(e3, s10, inc)).
evidence(e_activity(e3, s11, dec)).
evidence(e_activity(e3, s12, base)).
evidence(e_activity(e3, s14, base)).
evidence(e_activity(e3, s15, dec)).
evidence(e_activity(e3, s16, dec)).
evidence(e_activity(e3, s17, inc)).
evidence(e_activity(e3, s19, inc)).
evidence(e_activity(e3, s2, dec)).
evidence(e_activity(e3, s20, inc)).
evidence(e_activity(e3, s21, dec)).
evidence(e_activity(e3, s22, base)).
evidence(e_activity(e3, s23, dec)).
evidence(e_activity(e3, s25, dec)).
evidence(e_activity(e3, s27, dec)).
evidence(e_activity(e3, s28, dec)).
evidence(e_activity(e3, s29, dec)).
evidence(e_activity(e3, s3, base)).
evidence(e_activity(e3, s30, inc)).
evidence(e_activity(e3, s32, dec)).
evidence(e_activity(e3, s34, dec)).
evidence(e_activity(e3, s36, inc)).
evidence(e_activity(e3, s37, dec)).
evidence(e_activity(e3, s38, dec)).
evidence(e_activity(e3, s39, base)).
evidence(e_activity(e3, s4, inc)).
evidence(e_activity(e3, s40, base)).
evidence(e_activity(e3, s41, base)).
evidence(e_activity(e3, s42, inc)).
evidence(e_activity(e3, s43, base)).
evidence(e_activity(e3, s45, dec)).
evidence(e_activity(e3, s47, base)).
evidence(e_activity(e3, s48, inc)).
evidence(e_activity(e3, s49, dec)).
evidence(e_activity(e3, s5, inc)).
evidence(e_activity(e3, s50, base)).
evidence(e_activity(e3, s52, inc)).
evidence(e_activity(e3, s53, base)).
evidence(e_activity(e3, s54, inc)).
evidence(e_activity(e3, s56, dec)).
evidence(e_activity(e3, s57, base)).
evidence(e_activity(e3, s58, dec)).
evidence(e_activity(e3, s59, dec)).
evidence(e_activity(e3, s6, dec)).
evidence(e_activity(e3, s61, dec)).
evidence(e_activity(e3, s62, base)).
evidence(e_activity(e3, s63, inc)).
evidence(e_activity(e3, s64, dec)).
evidence(e_activity(e3, s66, inc)).
evidence(e_activity(e3, s67, inc)).
evidence(e_activity(e3, s68, inc)).
evidence(e_activity(e3, s69, inc)).
evidence(e_activity(e3, s7, inc)).
evidence(e_activity(e3, s70, base)).
evidence(e_activity(e3, s71, base)).
evidence(e_activity(e3, s72, inc)).
evidence(e_activity(e3, s74, dec)).
evidence(e_activity(e3, s75, dec)).
evidence(e_activity(e3, s76, dec)).
evidence(e_activity(e3, s77, dec)).
evidence(e_activity(e3, s8, base)).
evidence(e_activity(e3, s80, dec)).
evidence(e_activity(e3, s81, base)).
evidence(e_activity(e3, s82, base)).
evidence(e_activity(e3, s83, dec)).
evidence(e_activity(e3, s84, inc)).
evidence(e_activity(e3, s85, inc)).
evidence(e_activity(e3, s86, base)).
evidence(e_activity(e3, s87, inc)).
evidence(e_activity(e3, s88, inc)).
evidence(e_activity(e3, s89, inc)).
evidence(e_activity(e3, s90, dec)).
evidence(e_activity(e3, s91, base)).
evidence(e_activity(e3, s92, base)).
evidence(e_activity(e3, s93, base)).
evidence(e_activity(e3, s94, dec)).
evidence(e_activity(e3, s96, inc)).
evidence(e_activity(e3, s97, inc)).
evidence(e_activity(e3, s99, inc)).
evidence(p_occupancy(p0, s1, dec)).
evidence(p_occupancy(p0, s10, dec)).
evidence(p_occupancy(p0, s11, inc)).
evidence(p_occupancy(p0, s12, dec)).
evidence(p_occupancy(p0, s14, inc)).
evidence(p_occupancy(p0, s15, inc)).
evidence(p_occupancy(p0, s16, inc)).
evidence(p_occupancy(p0, s17, dec)).
evidence(p_occupancy(p0, s19, dec)).
evidence(p_occupancy(p0, s2, inc)).
evidence(p_occupancy(p0, s20, dec)).
evidence(p_occupancy(p0, s21, inc)).
evidence(p_occupancy(p0, s22, dec)).
evidence(p_occupancy(p0, s23, inc)).
evidence(p_occupancy(p0, s25, inc)).
evidence(p_occupancy(p0, s27, inc)).
evidence(p_occupancy(p0, s28, inc)).
evidence(p_occupancy(p0, s29, inc)).
evidence(p_occupancy(p0, s3, dec)).
evidence(p_occupancy(p0, s30, dec)).
evidence(p_occupancy(p0, s32, inc)).
evidence(p_occupancy(p0, s34, inc)).
evidence(p_occupancy(p0, s36, base)).
evidence(p_occupancy(p0, s37, inc)).
evidence(p_occupancy(p0, s38, base)).
evidence(p_occupancy(p0, s39, dec)).
evidence(p_occupancy(p0, s4, base)).
evidence(p_occupancy(p0, s40, dec)).
evidence(p_occupancy(p0, s41, inc)).
evidence(p_occupancy(p0, s42, dec)).
evidence(p_occupancy(p0, s43, base)).
evidence(p_occupancy(p0, s45, inc)).
evidence(p_occupancy(p0, s47, base)).
evidence(p_occupancy(p0, s48, base)).
evidence(p_occupancy(p0, s49, base)).
evidence(p_occupancy(p0, s5, base)).
evidence(p_occupancy(p0, s50, base)).
evidence(p_occupancy(p0, s52, dec)).
evidence(p_occupancy(p0, s53, base)).
evidence(p_occupancy(p0, s54, dec)).
evidence(p_occupancy(p0, s56, inc)).
evidence(p_occupancy(p0, s57, dec)).
evidence(p_occupancy(p0, s58, base)).
evidence(p_occupancy(p0, s59, inc)).
evidence(p_occupancy(p0, s6, inc)).
evidence(p_occupancy(p0, s61, inc)).
evidence(p_occupancy(p0, s62, inc)).
evidence(p_occupancy(p0, s63, base)).
evidence(p_occupancy(p0, s64, inc)).
evidence(p_occupancy(p0, s66, dec)).
evidence(p_occupancy(p0, s67, base)).
evidence(p_occupancy(p0, s68, dec)).
evidence(p_occupancy(p0, s69, base)).
evidence(p_occupancy(p0, s7, dec)).
evidence(p_occupancy(p0, s70, inc)).
evidence(p_occupancy(p0, s71, inc)).
evidence(p_occupancy(p0, s72, dec)).
evidence(p_occupancy(p0, s74, inc)).
evidence(p_occupancy(p0, s75, inc)).
evidence(p_occupancy(p0, s76, dec)).
evidence(p_occupancy(p0, s77, inc)).
evidence(p_occupancy(p0, s8, base)).
evidence(p_occupancy(p0, s80, base)).
evidence(p_occupancy(p0, s81, inc)).
evidence(p_occupancy(p0, s82, inc)).
evidence(p_occupancy(p0, s83, dec)).
evidence(p_occupancy(p0, s84, dec)).
evidence(p_occupancy(p0, s85, dec)).
evidence(p_occupancy(p0, s86, inc)).
evidence(p_occupancy(p0, s87, dec)).
evidence(p_occupancy(p0, s88, dec)).
evidence(p_occupancy(p0, s89, base)).
evidence(p_occupancy(p0, s90, inc)).
evidence(p_occupancy(p0, s91, base)).
evidence(p_occupancy(p0, s92, dec)).
evidence(p_occupancy(p0, s93, dec)).
evidence(p_occupancy(p0, s94, inc)).
evidence(p_occupancy(p0, s96, dec)).
evidence(p_occupancy(p0, s97, dec)).
evidence(p_occupancy(p0, s99, base)).
