evidence(e_ksea(e1, s29, inc)).
evidence(e_ksea(e2, s29, dec)).
evidence(e_ksea(e3, s29, dec)).
evidence(e_ksea(e4, s29, inc)).
evidence(e_ksea(e5, s29, inc)).
evidence(e_ksea(e6, s29, inc)).
evidence(e_ksea(e7, s29, inc)).
evidence(e_ksea(e8, s29, inc)).
evidence(e_ksea(e9, s29, inc)).
evidence(e_ksea(e10, s29, inc)).
evidence(p_fc(p0, s29, inc)).
--------------------
evidence(e_ksea(e1, s54, base)).
evidence(e_ksea(e2, s54, dec)).
evidence(e_ksea(e3, s54, inc)).
evidence(e_ksea(e4, s54, base)).
evidence(e_ksea(e5, s54, base)).
evidence(e_ksea(e6, s54, base)).
evidence(e_ksea(e7, s54, base)).
evidence(e_ksea(e8, s54, base)).
evidence(e_ksea(e9, s54, base)).
evidence(e_ksea(e10, s54, base)).
evidence(p_fc(p0, s54, dec)).
--------------------
evidence(e_ksea(e1, s75, inc)).
evidence(e_ksea(e2, s75, inc)).
evidence(e_ksea(e3, s75, dec)).
evidence(e_ksea(e4, s75, inc)).
evidence(e_ksea(e5, s75, inc)).
evidence(e_ksea(e6, s75, inc)).
evidence(e_ksea(e7, s75, inc)).
evidence(e_ksea(e8, s75, inc)).
evidence(e_ksea(e9, s75, inc)).
evidence(e_ksea(e10, s75, inc)).
evidence(p_fc(p0, s75, inc)).
--------------------
evidence(e_ksea(e1, s20, dec)).
evidence(e_ksea(e2, s20, inc)).
evidence(e_ksea(e3, s20, inc)).
evidence(e_ksea(e4, s20, dec)).
evidence(e_ksea(e5, s20, dec)).
evidence(e_ksea(e6, s20, dec)).
evidence(e_ksea(e7, s20, dec)).
evidence(e_ksea(e8, s20, dec)).
evidence(e_ksea(e9, s20, dec)).
evidence(e_ksea(e10, s20, dec)).
evidence(p_fc(p0, s20, dec)).
--------------------
evidence(e_ksea(e1, s65, inc)).
evidence(e_ksea(e2, s65, dec)).
evidence(e_ksea(e3, s65, inc)).
evidence(e_ksea(e4, s65, inc)).
evidence(e_ksea(e5, s65, inc)).
evidence(e_ksea(e6, s65, inc)).
evidence(e_ksea(e7, s65, inc)).
evidence(e_ksea(e8, s65, inc)).
evidence(e_ksea(e9, s65, inc)).
evidence(e_ksea(e10, s65, inc)).
evidence(p_fc(p0, s65, dec)).
--------------------
evidence(e_ksea(e1, s69, base)).
evidence(e_ksea(e2, s69, inc)).
evidence(e_ksea(e3, s69, inc)).
evidence(e_ksea(e4, s69, base)).
evidence(e_ksea(e5, s69, base)).
evidence(e_ksea(e6, s69, base)).
evidence(e_ksea(e7, s69, base)).
evidence(e_ksea(e8, s69, base)).
evidence(e_ksea(e9, s69, base)).
evidence(e_ksea(e10, s69, base)).
evidence(p_fc(p0, s69, base)).
--------------------
evidence(e_ksea(e1, s63, inc)).
evidence(e_ksea(e2, s63, base)).
evidence(e_ksea(e3, s63, inc)).
evidence(e_ksea(e4, s63, inc)).
evidence(e_ksea(e5, s63, inc)).
evidence(e_ksea(e6, s63, inc)).
evidence(e_ksea(e7, s63, inc)).
evidence(e_ksea(e8, s63, inc)).
evidence(e_ksea(e9, s63, inc)).
evidence(e_ksea(e10, s63, inc)).
evidence(p_fc(p0, s63, base)).
--------------------
evidence(e_ksea(e1, s95, dec)).
evidence(e_ksea(e2, s95, inc)).
evidence(e_ksea(e3, s95, inc)).
evidence(e_ksea(e4, s95, dec)).
evidence(e_ksea(e5, s95, dec)).
evidence(e_ksea(e6, s95, dec)).
evidence(e_ksea(e7, s95, dec)).
evidence(e_ksea(e8, s95, dec)).
evidence(e_ksea(e9, s95, dec)).
evidence(e_ksea(e10, s95, dec)).
evidence(p_fc(p0, s95, dec)).
--------------------
evidence(e_ksea(e1, s17, base)).
evidence(e_ksea(e2, s17, dec)).
evidence(e_ksea(e3, s17, inc)).
evidence(e_ksea(e4, s17, base)).
evidence(e_ksea(e5, s17, base)).
evidence(e_ksea(e6, s17, base)).
evidence(e_ksea(e7, s17, base)).
evidence(e_ksea(e8, s17, base)).
evidence(e_ksea(e9, s17, base)).
evidence(e_ksea(e10, s17, base)).
evidence(p_fc(p0, s17, dec)).
--------------------
evidence(e_ksea(e1, s96, base)).
evidence(e_ksea(e2, s96, dec)).
evidence(e_ksea(e3, s96, inc)).
evidence(e_ksea(e4, s96, base)).
evidence(e_ksea(e5, s96, base)).
evidence(e_ksea(e6, s96, base)).
evidence(e_ksea(e7, s96, base)).
evidence(e_ksea(e8, s96, base)).
evidence(e_ksea(e9, s96, base)).
evidence(e_ksea(e10, s96, base)).
evidence(p_fc(p0, s96, dec)).
--------------------
evidence(e_ksea(e1, s18, inc)).
evidence(e_ksea(e2, s18, base)).
evidence(e_ksea(e3, s18, dec)).
evidence(e_ksea(e4, s18, inc)).
evidence(e_ksea(e5, s18, inc)).
evidence(e_ksea(e6, s18, inc)).
evidence(e_ksea(e7, s18, inc)).
evidence(e_ksea(e8, s18, inc)).
evidence(e_ksea(e9, s18, inc)).
evidence(e_ksea(e10, s18, inc)).
evidence(p_fc(p0, s18, inc)).
--------------------
evidence(e_ksea(e1, s64, inc)).
evidence(e_ksea(e2, s64, inc)).
evidence(e_ksea(e3, s64, dec)).
evidence(e_ksea(e4, s64, inc)).
evidence(e_ksea(e5, s64, inc)).
evidence(e_ksea(e6, s64, inc)).
evidence(e_ksea(e7, s64, inc)).
evidence(e_ksea(e8, s64, inc)).
evidence(e_ksea(e9, s64, inc)).
evidence(e_ksea(e10, s64, inc)).
evidence(p_fc(p0, s64, inc)).
--------------------
evidence(e_ksea(e1, s99, inc)).
evidence(e_ksea(e2, s99, base)).
evidence(e_ksea(e3, s99, inc)).
evidence(e_ksea(e4, s99, inc)).
evidence(e_ksea(e5, s99, inc)).
evidence(e_ksea(e6, s99, inc)).
evidence(e_ksea(e7, s99, inc)).
evidence(e_ksea(e8, s99, inc)).
evidence(e_ksea(e9, s99, inc)).
evidence(e_ksea(e10, s99, inc)).
evidence(p_fc(p0, s99, base)).
--------------------
evidence(e_ksea(e1, s23, inc)).
evidence(e_ksea(e2, s23, base)).
evidence(e_ksea(e3, s23, dec)).
evidence(e_ksea(e4, s23, inc)).
evidence(e_ksea(e5, s23, inc)).
evidence(e_ksea(e6, s23, inc)).
evidence(e_ksea(e7, s23, inc)).
evidence(e_ksea(e8, s23, inc)).
evidence(e_ksea(e9, s23, inc)).
evidence(e_ksea(e10, s23, inc)).
evidence(p_fc(p0, s23, inc)).
--------------------
evidence(e_ksea(e1, s25, inc)).
evidence(e_ksea(e2, s25, dec)).
evidence(e_ksea(e3, s25, dec)).
evidence(e_ksea(e4, s25, inc)).
evidence(e_ksea(e5, s25, inc)).
evidence(e_ksea(e6, s25, inc)).
evidence(e_ksea(e7, s25, inc)).
evidence(e_ksea(e8, s25, inc)).
evidence(e_ksea(e9, s25, inc)).
evidence(e_ksea(e10, s25, inc)).
evidence(p_fc(p0, s25, inc)).
--------------------
evidence(e_ksea(e1, s28, inc)).
evidence(e_ksea(e2, s28, dec)).
evidence(e_ksea(e3, s28, dec)).
evidence(e_ksea(e4, s28, inc)).
evidence(e_ksea(e5, s28, inc)).
evidence(e_ksea(e6, s28, inc)).
evidence(e_ksea(e7, s28, inc)).
evidence(e_ksea(e8, s28, inc)).
evidence(e_ksea(e9, s28, inc)).
evidence(e_ksea(e10, s28, inc)).
evidence(p_fc(p0, s28, inc)).
--------------------
evidence(e_ksea(e1, s22, base)).
evidence(e_ksea(e2, s22, dec)).
evidence(e_ksea(e3, s22, base)).
evidence(e_ksea(e4, s22, base)).
evidence(e_ksea(e5, s22, base)).
evidence(e_ksea(e6, s22, base)).
evidence(e_ksea(e7, s22, base)).
evidence(e_ksea(e8, s22, base)).
evidence(e_ksea(e9, s22, base)).
evidence(e_ksea(e10, s22, base)).
evidence(p_fc(p0, s22, dec)).
--------------------
evidence(e_ksea(e1, s27, inc)).
evidence(e_ksea(e2, s27, dec)).
evidence(e_ksea(e3, s27, dec)).
evidence(e_ksea(e4, s27, inc)).
evidence(e_ksea(e5, s27, inc)).
evidence(e_ksea(e6, s27, inc)).
evidence(e_ksea(e7, s27, inc)).
evidence(e_ksea(e8, s27, inc)).
evidence(e_ksea(e9, s27, inc)).
evidence(e_ksea(e10, s27, inc)).
evidence(p_fc(p0, s27, inc)).
--------------------
evidence(e_ksea(e1, s82, inc)).
evidence(e_ksea(e2, s82, base)).
evidence(e_ksea(e3, s82, base)).
evidence(e_ksea(e4, s82, inc)).
evidence(e_ksea(e5, s82, inc)).
evidence(e_ksea(e6, s82, inc)).
evidence(e_ksea(e7, s82, inc)).
evidence(e_ksea(e8, s82, inc)).
evidence(e_ksea(e9, s82, inc)).
evidence(e_ksea(e10, s82, inc)).
evidence(p_fc(p0, s82, inc)).
--------------------
evidence(e_ksea(e1, s3, dec)).
evidence(e_ksea(e2, s3, dec)).
evidence(e_ksea(e3, s3, base)).
evidence(e_ksea(e4, s3, dec)).
evidence(e_ksea(e5, s3, dec)).
evidence(e_ksea(e6, s3, dec)).
evidence(e_ksea(e7, s3, dec)).
evidence(e_ksea(e8, s3, dec)).
evidence(e_ksea(e9, s3, dec)).
evidence(e_ksea(e10, s3, dec)).
evidence(p_fc(p0, s3, dec)).
--------------------
evidence(e_ksea(e1, s50, dec)).
evidence(e_ksea(e2, s50, inc)).
evidence(e_ksea(e3, s50, base)).
evidence(e_ksea(e4, s50, dec)).
evidence(e_ksea(e5, s50, dec)).
evidence(e_ksea(e6, s50, dec)).
evidence(e_ksea(e7, s50, dec)).
evidence(e_ksea(e8, s50, dec)).
evidence(e_ksea(e9, s50, dec)).
evidence(e_ksea(e10, s50, dec)).
evidence(p_fc(p0, s50, base)).
--------------------
evidence(e_ksea(e1, s1, inc)).
evidence(e_ksea(e2, s1, dec)).
evidence(e_ksea(e3, s1, inc)).
evidence(e_ksea(e4, s1, inc)).
evidence(e_ksea(e5, s1, inc)).
evidence(e_ksea(e6, s1, inc)).
evidence(e_ksea(e7, s1, inc)).
evidence(e_ksea(e8, s1, inc)).
evidence(e_ksea(e9, s1, inc)).
evidence(e_ksea(e10, s1, inc)).
evidence(p_fc(p0, s1, dec)).
--------------------
evidence(e_ksea(e1, s9, base)).
evidence(e_ksea(e2, s9, base)).
evidence(e_ksea(e3, s9, base)).
evidence(e_ksea(e4, s9, base)).
evidence(e_ksea(e5, s9, base)).
evidence(e_ksea(e6, s9, base)).
evidence(e_ksea(e7, s9, base)).
evidence(e_ksea(e8, s9, base)).
evidence(e_ksea(e9, s9, base)).
evidence(e_ksea(e10, s9, base)).
evidence(p_fc(p0, s9, base)).
--------------------
evidence(e_ksea(e1, s31, base)).
evidence(e_ksea(e2, s31, inc)).
evidence(e_ksea(e3, s31, dec)).
evidence(e_ksea(e4, s31, base)).
evidence(e_ksea(e5, s31, base)).
evidence(e_ksea(e6, s31, base)).
evidence(e_ksea(e7, s31, base)).
evidence(e_ksea(e8, s31, base)).
evidence(e_ksea(e9, s31, base)).
evidence(e_ksea(e10, s31, base)).
evidence(p_fc(p0, s31, inc)).
--------------------
evidence(e_ksea(e1, s87, dec)).
evidence(e_ksea(e2, s87, base)).
evidence(e_ksea(e3, s87, inc)).
evidence(e_ksea(e4, s87, dec)).
evidence(e_ksea(e5, s87, dec)).
evidence(e_ksea(e6, s87, dec)).
evidence(e_ksea(e7, s87, dec)).
evidence(e_ksea(e8, s87, dec)).
evidence(e_ksea(e9, s87, dec)).
evidence(e_ksea(e10, s87, dec)).
evidence(p_fc(p0, s87, dec)).
--------------------
evidence(e_ksea(e1, s16, base)).
evidence(e_ksea(e2, s16, base)).
evidence(e_ksea(e3, s16, dec)).
evidence(e_ksea(e4, s16, base)).
evidence(e_ksea(e5, s16, base)).
evidence(e_ksea(e6, s16, base)).
evidence(e_ksea(e7, s16, base)).
evidence(e_ksea(e8, s16, base)).
evidence(e_ksea(e9, s16, base)).
evidence(e_ksea(e10, s16, base)).
evidence(p_fc(p0, s16, inc)).
--------------------
evidence(e_ksea(e1, s78, base)).
evidence(e_ksea(e2, s78, dec)).
evidence(e_ksea(e3, s78, inc)).
evidence(e_ksea(e4, s78, base)).
evidence(e_ksea(e5, s78, base)).
evidence(e_ksea(e6, s78, base)).
evidence(e_ksea(e7, s78, base)).
evidence(e_ksea(e8, s78, base)).
evidence(e_ksea(e9, s78, base)).
evidence(e_ksea(e10, s78, base)).
evidence(p_fc(p0, s78, dec)).
--------------------
evidence(e_ksea(e1, s34, inc)).
evidence(e_ksea(e2, s34, base)).
evidence(e_ksea(e3, s34, dec)).
evidence(e_ksea(e4, s34, inc)).
evidence(e_ksea(e5, s34, inc)).
evidence(e_ksea(e6, s34, inc)).
evidence(e_ksea(e7, s34, inc)).
evidence(e_ksea(e8, s34, inc)).
evidence(e_ksea(e9, s34, inc)).
evidence(e_ksea(e10, s34, inc)).
evidence(p_fc(p0, s34, inc)).
--------------------
evidence(e_ksea(e1, s91, inc)).
evidence(e_ksea(e2, s91, dec)).
evidence(e_ksea(e3, s91, base)).
evidence(e_ksea(e4, s91, inc)).
evidence(e_ksea(e5, s91, inc)).
evidence(e_ksea(e6, s91, inc)).
evidence(e_ksea(e7, s91, inc)).
evidence(e_ksea(e8, s91, inc)).
evidence(e_ksea(e9, s91, inc)).
evidence(e_ksea(e10, s91, inc)).
evidence(p_fc(p0, s91, base)).
--------------------
evidence(e_ksea(e1, s4, base)).
evidence(e_ksea(e2, s4, inc)).
evidence(e_ksea(e3, s4, inc)).
evidence(e_ksea(e4, s4, base)).
evidence(e_ksea(e5, s4, base)).
evidence(e_ksea(e6, s4, base)).
evidence(e_ksea(e7, s4, base)).
evidence(e_ksea(e8, s4, base)).
evidence(e_ksea(e9, s4, base)).
evidence(e_ksea(e10, s4, base)).
evidence(p_fc(p0, s4, base)).
--------------------
evidence(e_ksea(e1, s5, inc)).
evidence(e_ksea(e2, s5, base)).
evidence(e_ksea(e3, s5, inc)).
evidence(e_ksea(e4, s5, inc)).
evidence(e_ksea(e5, s5, inc)).
evidence(e_ksea(e6, s5, inc)).
evidence(e_ksea(e7, s5, inc)).
evidence(e_ksea(e8, s5, inc)).
evidence(e_ksea(e9, s5, inc)).
evidence(e_ksea(e10, s5, inc)).
evidence(p_fc(p0, s5, base)).
--------------------
evidence(e_ksea(e1, s70, inc)).
evidence(e_ksea(e2, s70, base)).
evidence(e_ksea(e3, s70, base)).
evidence(e_ksea(e4, s70, inc)).
evidence(e_ksea(e5, s70, inc)).
evidence(e_ksea(e6, s70, inc)).
evidence(e_ksea(e7, s70, inc)).
evidence(e_ksea(e8, s70, inc)).
evidence(e_ksea(e9, s70, inc)).
evidence(e_ksea(e10, s70, inc)).
evidence(p_fc(p0, s70, inc)).
--------------------
evidence(e_ksea(e1, s33, dec)).
evidence(e_ksea(e2, s33, base)).
evidence(e_ksea(e3, s33, base)).
evidence(e_ksea(e4, s33, dec)).
evidence(e_ksea(e5, s33, dec)).
evidence(e_ksea(e6, s33, dec)).
evidence(e_ksea(e7, s33, dec)).
evidence(e_ksea(e8, s33, dec)).
evidence(e_ksea(e9, s33, dec)).
evidence(e_ksea(e10, s33, dec)).
evidence(p_fc(p0, s33, dec)).
--------------------
evidence(e_ksea(e1, s53, inc)).
evidence(e_ksea(e2, s53, dec)).
evidence(e_ksea(e3, s53, base)).
evidence(e_ksea(e4, s53, inc)).
evidence(e_ksea(e5, s53, inc)).
evidence(e_ksea(e6, s53, inc)).
evidence(e_ksea(e7, s53, inc)).
evidence(e_ksea(e8, s53, inc)).
evidence(e_ksea(e9, s53, inc)).
evidence(e_ksea(e10, s53, inc)).
evidence(p_fc(p0, s53, base)).
--------------------
evidence(e_ksea(e1, s51, dec)).
evidence(e_ksea(e2, s51, base)).
evidence(e_ksea(e3, s51, dec)).
evidence(e_ksea(e4, s51, dec)).
evidence(e_ksea(e5, s51, dec)).
evidence(e_ksea(e6, s51, dec)).
evidence(e_ksea(e7, s51, dec)).
evidence(e_ksea(e8, s51, dec)).
evidence(e_ksea(e9, s51, dec)).
evidence(e_ksea(e10, s51, dec)).
evidence(p_fc(p0, s51, base)).
--------------------
evidence(e_ksea(e1, s44, dec)).
evidence(e_ksea(e2, s44, base)).
evidence(e_ksea(e3, s44, base)).
evidence(e_ksea(e4, s44, dec)).
evidence(e_ksea(e5, s44, dec)).
evidence(e_ksea(e6, s44, dec)).
evidence(e_ksea(e7, s44, dec)).
evidence(e_ksea(e8, s44, dec)).
evidence(e_ksea(e9, s44, dec)).
evidence(e_ksea(e10, s44, dec)).
evidence(p_fc(p0, s44, dec)).
--------------------
evidence(e_ksea(e1, s100, inc)).
evidence(e_ksea(e2, s100, inc)).
evidence(e_ksea(e3, s100, dec)).
evidence(e_ksea(e4, s100, inc)).
evidence(e_ksea(e5, s100, inc)).
evidence(e_ksea(e6, s100, inc)).
evidence(e_ksea(e7, s100, inc)).
evidence(e_ksea(e8, s100, inc)).
evidence(e_ksea(e9, s100, inc)).
evidence(e_ksea(e10, s100, inc)).
evidence(p_fc(p0, s100, inc)).
--------------------
evidence(e_ksea(e1, s32, inc)).
evidence(e_ksea(e2, s32, inc)).
evidence(e_ksea(e3, s32, dec)).
evidence(e_ksea(e4, s32, inc)).
evidence(e_ksea(e5, s32, inc)).
evidence(e_ksea(e6, s32, inc)).
evidence(e_ksea(e7, s32, inc)).
evidence(e_ksea(e8, s32, inc)).
evidence(e_ksea(e9, s32, inc)).
evidence(e_ksea(e10, s32, inc)).
evidence(p_fc(p0, s32, inc)).
--------------------
evidence(e_ksea(e1, s86, inc)).
evidence(e_ksea(e2, s86, inc)).
evidence(e_ksea(e3, s86, base)).
evidence(e_ksea(e4, s86, inc)).
evidence(e_ksea(e5, s86, inc)).
evidence(e_ksea(e6, s86, inc)).
evidence(e_ksea(e7, s86, inc)).
evidence(e_ksea(e8, s86, inc)).
evidence(e_ksea(e9, s86, inc)).
evidence(e_ksea(e10, s86, inc)).
evidence(p_fc(p0, s86, inc)).
--------------------
evidence(e_ksea(e1, s58, dec)).
evidence(e_ksea(e2, s58, base)).
evidence(e_ksea(e3, s58, dec)).
evidence(e_ksea(e4, s58, dec)).
evidence(e_ksea(e5, s58, dec)).
evidence(e_ksea(e6, s58, dec)).
evidence(e_ksea(e7, s58, dec)).
evidence(e_ksea(e8, s58, dec)).
evidence(e_ksea(e9, s58, dec)).
evidence(e_ksea(e10, s58, dec)).
evidence(p_fc(p0, s58, base)).
--------------------
evidence(e_ksea(e1, s68, dec)).
evidence(e_ksea(e2, s68, inc)).
evidence(e_ksea(e3, s68, inc)).
evidence(e_ksea(e4, s68, dec)).
evidence(e_ksea(e5, s68, dec)).
evidence(e_ksea(e6, s68, dec)).
evidence(e_ksea(e7, s68, dec)).
evidence(e_ksea(e8, s68, dec)).
evidence(e_ksea(e9, s68, dec)).
evidence(e_ksea(e10, s68, dec)).
evidence(p_fc(p0, s68, dec)).
--------------------
evidence(e_ksea(e1, s39, dec)).
evidence(e_ksea(e2, s39, base)).
evidence(e_ksea(e3, s39, base)).
evidence(e_ksea(e4, s39, dec)).
evidence(e_ksea(e5, s39, dec)).
evidence(e_ksea(e6, s39, dec)).
evidence(e_ksea(e7, s39, dec)).
evidence(e_ksea(e8, s39, dec)).
evidence(e_ksea(e9, s39, dec)).
evidence(e_ksea(e10, s39, dec)).
evidence(p_fc(p0, s39, dec)).
--------------------
evidence(e_ksea(e1, s73, base)).
evidence(e_ksea(e2, s73, dec)).
evidence(e_ksea(e3, s73, dec)).
evidence(e_ksea(e4, s73, base)).
evidence(e_ksea(e5, s73, base)).
evidence(e_ksea(e6, s73, base)).
evidence(e_ksea(e7, s73, base)).
evidence(e_ksea(e8, s73, base)).
evidence(e_ksea(e9, s73, base)).
evidence(e_ksea(e10, s73, base)).
evidence(p_fc(p0, s73, base)).
--------------------
evidence(e_ksea(e1, s77, inc)).
evidence(e_ksea(e2, s77, inc)).
evidence(e_ksea(e3, s77, dec)).
evidence(e_ksea(e4, s77, inc)).
evidence(e_ksea(e5, s77, inc)).
evidence(e_ksea(e6, s77, inc)).
evidence(e_ksea(e7, s77, inc)).
evidence(e_ksea(e8, s77, inc)).
evidence(e_ksea(e9, s77, inc)).
evidence(e_ksea(e10, s77, inc)).
evidence(p_fc(p0, s77, inc)).
--------------------
evidence(e_ksea(e1, s84, dec)).
evidence(e_ksea(e2, s84, base)).
evidence(e_ksea(e3, s84, inc)).
evidence(e_ksea(e4, s84, dec)).
evidence(e_ksea(e5, s84, dec)).
evidence(e_ksea(e6, s84, dec)).
evidence(e_ksea(e7, s84, dec)).
evidence(e_ksea(e8, s84, dec)).
evidence(e_ksea(e9, s84, dec)).
evidence(e_ksea(e10, s84, dec)).
evidence(p_fc(p0, s84, dec)).
--------------------
evidence(e_ksea(e1, s2, inc)).
evidence(e_ksea(e2, s2, dec)).
evidence(e_ksea(e3, s2, dec)).
evidence(e_ksea(e4, s2, inc)).
evidence(e_ksea(e5, s2, inc)).
evidence(e_ksea(e6, s2, inc)).
evidence(e_ksea(e7, s2, inc)).
evidence(e_ksea(e8, s2, inc)).
evidence(e_ksea(e9, s2, inc)).
evidence(e_ksea(e10, s2, inc)).
evidence(p_fc(p0, s2, inc)).
--------------------
evidence(e_ksea(e1, s90, inc)).
evidence(e_ksea(e2, s90, base)).
evidence(e_ksea(e3, s90, dec)).
evidence(e_ksea(e4, s90, inc)).
evidence(e_ksea(e5, s90, inc)).
evidence(e_ksea(e6, s90, inc)).
evidence(e_ksea(e7, s90, inc)).
evidence(e_ksea(e8, s90, inc)).
evidence(e_ksea(e9, s90, inc)).
evidence(e_ksea(e10, s90, inc)).
evidence(p_fc(p0, s90, inc)).
--------------------
evidence(e_ksea(e1, s66, inc)).
evidence(e_ksea(e2, s66, dec)).
evidence(e_ksea(e3, s66, inc)).
evidence(e_ksea(e4, s66, inc)).
evidence(e_ksea(e5, s66, inc)).
evidence(e_ksea(e6, s66, inc)).
evidence(e_ksea(e7, s66, inc)).
evidence(e_ksea(e8, s66, inc)).
evidence(e_ksea(e9, s66, inc)).
evidence(e_ksea(e10, s66, inc)).
evidence(p_fc(p0, s66, dec)).
--------------------
evidence(e_ksea(e1, s79, base)).
evidence(e_ksea(e2, s79, inc)).
evidence(e_ksea(e3, s79, base)).
evidence(e_ksea(e4, s79, base)).
evidence(e_ksea(e5, s79, base)).
evidence(e_ksea(e6, s79, base)).
evidence(e_ksea(e7, s79, base)).
evidence(e_ksea(e8, s79, base)).
evidence(e_ksea(e9, s79, base)).
evidence(e_ksea(e10, s79, base)).
evidence(p_fc(p0, s79, inc)).
--------------------
evidence(e_ksea(e1, s72, dec)).
evidence(e_ksea(e2, s72, dec)).
evidence(e_ksea(e3, s72, inc)).
evidence(e_ksea(e4, s72, dec)).
evidence(e_ksea(e5, s72, dec)).
evidence(e_ksea(e6, s72, dec)).
evidence(e_ksea(e7, s72, dec)).
evidence(e_ksea(e8, s72, dec)).
evidence(e_ksea(e9, s72, dec)).
evidence(e_ksea(e10, s72, dec)).
evidence(p_fc(p0, s72, dec)).
--------------------
evidence(e_ksea(e1, s6, base)).
evidence(e_ksea(e2, s6, inc)).
evidence(e_ksea(e3, s6, dec)).
evidence(e_ksea(e4, s6, base)).
evidence(e_ksea(e5, s6, base)).
evidence(e_ksea(e6, s6, base)).
evidence(e_ksea(e7, s6, base)).
evidence(e_ksea(e8, s6, base)).
evidence(e_ksea(e9, s6, base)).
evidence(e_ksea(e10, s6, base)).
evidence(p_fc(p0, s6, inc)).
--------------------
evidence(e_ksea(e1, s98, inc)).
evidence(e_ksea(e2, s98, inc)).
evidence(e_ksea(e3, s98, dec)).
evidence(e_ksea(e4, s98, inc)).
evidence(e_ksea(e5, s98, inc)).
evidence(e_ksea(e6, s98, inc)).
evidence(e_ksea(e7, s98, inc)).
evidence(e_ksea(e8, s98, inc)).
evidence(e_ksea(e9, s98, inc)).
evidence(e_ksea(e10, s98, inc)).
evidence(p_fc(p0, s98, inc)).
--------------------
evidence(e_ksea(e1, s30, inc)).
evidence(e_ksea(e2, s30, dec)).
evidence(e_ksea(e3, s30, inc)).
evidence(e_ksea(e4, s30, inc)).
evidence(e_ksea(e5, s30, inc)).
evidence(e_ksea(e6, s30, inc)).
evidence(e_ksea(e7, s30, inc)).
evidence(e_ksea(e8, s30, inc)).
evidence(e_ksea(e9, s30, inc)).
evidence(e_ksea(e10, s30, inc)).
evidence(p_fc(p0, s30, dec)).
--------------------
evidence(e_ksea(e1, s35, inc)).
evidence(e_ksea(e2, s35, base)).
evidence(e_ksea(e3, s35, base)).
evidence(e_ksea(e4, s35, inc)).
evidence(e_ksea(e5, s35, inc)).
evidence(e_ksea(e6, s35, inc)).
evidence(e_ksea(e7, s35, inc)).
evidence(e_ksea(e8, s35, inc)).
evidence(e_ksea(e9, s35, inc)).
evidence(e_ksea(e10, s35, inc)).
evidence(p_fc(p0, s35, inc)).
--------------------
evidence(e_ksea(e1, s14, base)).
evidence(e_ksea(e2, s14, inc)).
evidence(e_ksea(e3, s14, base)).
evidence(e_ksea(e4, s14, base)).
evidence(e_ksea(e5, s14, base)).
evidence(e_ksea(e6, s14, base)).
evidence(e_ksea(e7, s14, base)).
evidence(e_ksea(e8, s14, base)).
evidence(e_ksea(e9, s14, base)).
evidence(e_ksea(e10, s14, base)).
evidence(p_fc(p0, s14, inc)).
--------------------
evidence(e_ksea(e1, s94, dec)).
evidence(e_ksea(e2, s94, inc)).
evidence(e_ksea(e3, s94, dec)).
evidence(e_ksea(e4, s94, dec)).
evidence(e_ksea(e5, s94, dec)).
evidence(e_ksea(e6, s94, dec)).
evidence(e_ksea(e7, s94, dec)).
evidence(e_ksea(e8, s94, dec)).
evidence(e_ksea(e9, s94, dec)).
evidence(e_ksea(e10, s94, dec)).
evidence(p_fc(p0, s94, inc)).
--------------------
evidence(e_ksea(e1, s85, base)).
evidence(e_ksea(e2, s85, dec)).
evidence(e_ksea(e3, s85, inc)).
evidence(e_ksea(e4, s85, base)).
evidence(e_ksea(e5, s85, base)).
evidence(e_ksea(e6, s85, base)).
evidence(e_ksea(e7, s85, base)).
evidence(e_ksea(e8, s85, base)).
evidence(e_ksea(e9, s85, base)).
evidence(e_ksea(e10, s85, base)).
evidence(p_fc(p0, s85, dec)).
--------------------
evidence(e_ksea(e1, s71, inc)).
evidence(e_ksea(e2, s71, inc)).
evidence(e_ksea(e3, s71, base)).
evidence(e_ksea(e4, s71, inc)).
evidence(e_ksea(e5, s71, inc)).
evidence(e_ksea(e6, s71, inc)).
evidence(e_ksea(e7, s71, inc)).
evidence(e_ksea(e8, s71, inc)).
evidence(e_ksea(e9, s71, inc)).
evidence(e_ksea(e10, s71, inc)).
evidence(p_fc(p0, s71, inc)).
--------------------
evidence(e_ksea(e1, s89, inc)).
evidence(e_ksea(e2, s89, base)).
evidence(e_ksea(e3, s89, inc)).
evidence(e_ksea(e4, s89, inc)).
evidence(e_ksea(e5, s89, inc)).
evidence(e_ksea(e6, s89, inc)).
evidence(e_ksea(e7, s89, inc)).
evidence(e_ksea(e8, s89, inc)).
evidence(e_ksea(e9, s89, inc)).
evidence(e_ksea(e10, s89, inc)).
evidence(p_fc(p0, s89, base)).
--------------------
evidence(e_ksea(e1, s81, inc)).
evidence(e_ksea(e2, s81, inc)).
evidence(e_ksea(e3, s81, base)).
evidence(e_ksea(e4, s81, inc)).
evidence(e_ksea(e5, s81, inc)).
evidence(e_ksea(e6, s81, inc)).
evidence(e_ksea(e7, s81, inc)).
evidence(e_ksea(e8, s81, inc)).
evidence(e_ksea(e9, s81, inc)).
evidence(e_ksea(e10, s81, inc)).
evidence(p_fc(p0, s81, inc)).
--------------------
