evidence(e_ksea(e1, s96, dec)).
evidence(e_ksea(e2, s96, dec)).
evidence(e_ksea(e3, s96, inc)).
evidence(p_fc(p0, s96, dec)).
evidence(p_fc(p1, s96, dec)).
evidence(p_fc(p2, s96, dec)).
evidence(p_fc(p3, s96, dec)).
evidence(p_fc(p4, s96, dec)).
evidence(p_fc(p5, s96, dec)).
evidence(p_fc(p6, s96, dec)).
evidence(p_fc(p7, s96, dec)).
evidence(p_fc(p8, s96, dec)).
evidence(p_fc(p9, s96, dec)).
--------------------
evidence(e_ksea(e1, s51, dec)).
evidence(e_ksea(e2, s51, dec)).
evidence(e_ksea(e3, s51, dec)).
evidence(p_fc(p0, s51, dec)).
evidence(p_fc(p1, s51, dec)).
evidence(p_fc(p2, s51, dec)).
evidence(p_fc(p3, s51, dec)).
evidence(p_fc(p4, s51, dec)).
evidence(p_fc(p5, s51, dec)).
evidence(p_fc(p6, s51, dec)).
evidence(p_fc(p7, s51, dec)).
evidence(p_fc(p8, s51, dec)).
evidence(p_fc(p9, s51, dec)).
--------------------
evidence(e_ksea(e1, s1, inc)).
evidence(e_ksea(e2, s1, dec)).
evidence(e_ksea(e3, s1, inc)).
evidence(p_fc(p0, s1, dec)).
evidence(p_fc(p1, s1, dec)).
evidence(p_fc(p2, s1, dec)).
evidence(p_fc(p3, s1, dec)).
evidence(p_fc(p4, s1, dec)).
evidence(p_fc(p5, s1, dec)).
evidence(p_fc(p6, s1, dec)).
evidence(p_fc(p7, s1, dec)).
evidence(p_fc(p8, s1, dec)).
evidence(p_fc(p9, s1, dec)).
--------------------
evidence(e_ksea(e1, s78, dec)).
evidence(e_ksea(e2, s78, dec)).
evidence(e_ksea(e3, s78, inc)).
evidence(p_fc(p0, s78, dec)).
evidence(p_fc(p1, s78, dec)).
evidence(p_fc(p2, s78, dec)).
evidence(p_fc(p3, s78, dec)).
evidence(p_fc(p4, s78, dec)).
evidence(p_fc(p5, s78, dec)).
evidence(p_fc(p6, s78, dec)).
evidence(p_fc(p7, s78, dec)).
evidence(p_fc(p8, s78, dec)).
evidence(p_fc(p9, s78, dec)).
--------------------
evidence(e_ksea(e1, s35, inc)).
evidence(e_ksea(e2, s35, inc)).
evidence(e_ksea(e3, s35, dec)).
evidence(p_fc(p0, s35, inc)).
evidence(p_fc(p1, s35, inc)).
evidence(p_fc(p2, s35, inc)).
evidence(p_fc(p3, s35, inc)).
evidence(p_fc(p4, s35, inc)).
evidence(p_fc(p5, s35, inc)).
evidence(p_fc(p6, s35, inc)).
evidence(p_fc(p7, s35, inc)).
evidence(p_fc(p8, s35, inc)).
evidence(p_fc(p9, s35, inc)).
--------------------
evidence(e_ksea(e1, s69, dec)).
evidence(e_ksea(e2, s69, inc)).
evidence(e_ksea(e3, s69, inc)).
evidence(p_fc(p0, s69, inc)).
evidence(p_fc(p1, s69, inc)).
evidence(p_fc(p2, s69, inc)).
evidence(p_fc(p3, s69, inc)).
evidence(p_fc(p4, s69, inc)).
evidence(p_fc(p5, s69, inc)).
evidence(p_fc(p6, s69, inc)).
evidence(p_fc(p7, s69, inc)).
evidence(p_fc(p8, s69, inc)).
evidence(p_fc(p9, s69, inc)).
--------------------
evidence(e_ksea(e1, s25, inc)).
evidence(e_ksea(e2, s25, dec)).
evidence(e_ksea(e3, s25, dec)).
evidence(p_fc(p0, s25, inc)).
evidence(p_fc(p1, s25, inc)).
evidence(p_fc(p2, s25, inc)).
evidence(p_fc(p3, s25, inc)).
evidence(p_fc(p4, s25, inc)).
evidence(p_fc(p5, s25, inc)).
evidence(p_fc(p6, s25, inc)).
evidence(p_fc(p7, s25, inc)).
evidence(p_fc(p8, s25, inc)).
evidence(p_fc(p9, s25, inc)).
--------------------
evidence(e_ksea(e1, s90, inc)).
evidence(e_ksea(e2, s90, dec)).
evidence(e_ksea(e3, s90, dec)).
evidence(p_fc(p0, s90, inc)).
evidence(p_fc(p1, s90, inc)).
evidence(p_fc(p2, s90, inc)).
evidence(p_fc(p3, s90, inc)).
evidence(p_fc(p4, s90, inc)).
evidence(p_fc(p5, s90, inc)).
evidence(p_fc(p6, s90, inc)).
evidence(p_fc(p7, s90, inc)).
evidence(p_fc(p8, s90, inc)).
evidence(p_fc(p9, s90, inc)).
--------------------
evidence(e_ksea(e1, s84, dec)).
evidence(e_ksea(e2, s84, inc)).
evidence(e_ksea(e3, s84, inc)).
evidence(p_fc(p0, s84, dec)).
evidence(p_fc(p1, s84, dec)).
evidence(p_fc(p2, s84, dec)).
evidence(p_fc(p3, s84, dec)).
evidence(p_fc(p4, s84, dec)).
evidence(p_fc(p5, s84, dec)).
evidence(p_fc(p6, s84, dec)).
evidence(p_fc(p7, s84, dec)).
evidence(p_fc(p8, s84, dec)).
evidence(p_fc(p9, s84, dec)).
--------------------
evidence(e_ksea(e1, s54, dec)).
evidence(e_ksea(e2, s54, dec)).
evidence(e_ksea(e3, s54, inc)).
evidence(p_fc(p0, s54, dec)).
evidence(p_fc(p1, s54, dec)).
evidence(p_fc(p2, s54, dec)).
evidence(p_fc(p3, s54, dec)).
evidence(p_fc(p4, s54, dec)).
evidence(p_fc(p5, s54, dec)).
evidence(p_fc(p6, s54, dec)).
evidence(p_fc(p7, s54, dec)).
evidence(p_fc(p8, s54, dec)).
evidence(p_fc(p9, s54, dec)).
--------------------
evidence(e_ksea(e1, s17, inc)).
evidence(e_ksea(e2, s17, dec)).
evidence(e_ksea(e3, s17, inc)).
evidence(p_fc(p0, s17, dec)).
evidence(p_fc(p1, s17, dec)).
evidence(p_fc(p2, s17, dec)).
evidence(p_fc(p3, s17, dec)).
evidence(p_fc(p4, s17, dec)).
evidence(p_fc(p5, s17, dec)).
evidence(p_fc(p6, s17, dec)).
evidence(p_fc(p7, s17, dec)).
evidence(p_fc(p8, s17, dec)).
evidence(p_fc(p9, s17, dec)).
--------------------
evidence(e_ksea(e1, s39, dec)).
evidence(e_ksea(e2, s39, inc)).
evidence(e_ksea(e3, s39, dec)).
evidence(p_fc(p0, s39, dec)).
evidence(p_fc(p1, s39, dec)).
evidence(p_fc(p2, s39, dec)).
evidence(p_fc(p3, s39, dec)).
evidence(p_fc(p4, s39, dec)).
evidence(p_fc(p5, s39, dec)).
evidence(p_fc(p6, s39, dec)).
evidence(p_fc(p7, s39, dec)).
evidence(p_fc(p8, s39, dec)).
evidence(p_fc(p9, s39, dec)).
--------------------
evidence(e_ksea(e1, s100, inc)).
evidence(e_ksea(e2, s100, inc)).
evidence(e_ksea(e3, s100, dec)).
evidence(p_fc(p0, s100, inc)).
evidence(p_fc(p1, s100, inc)).
evidence(p_fc(p2, s100, inc)).
evidence(p_fc(p3, s100, inc)).
evidence(p_fc(p4, s100, inc)).
evidence(p_fc(p5, s100, inc)).
evidence(p_fc(p6, s100, inc)).
evidence(p_fc(p7, s100, inc)).
evidence(p_fc(p8, s100, inc)).
evidence(p_fc(p9, s100, inc)).
--------------------
evidence(e_ksea(e1, s70, inc)).
evidence(e_ksea(e2, s70, dec)).
evidence(e_ksea(e3, s70, dec)).
evidence(p_fc(p0, s70, inc)).
evidence(p_fc(p1, s70, inc)).
evidence(p_fc(p2, s70, inc)).
evidence(p_fc(p3, s70, inc)).
evidence(p_fc(p4, s70, inc)).
evidence(p_fc(p5, s70, inc)).
evidence(p_fc(p6, s70, inc)).
evidence(p_fc(p7, s70, inc)).
evidence(p_fc(p8, s70, inc)).
evidence(p_fc(p9, s70, inc)).
--------------------
evidence(e_ksea(e1, s94, dec)).
evidence(e_ksea(e2, s94, inc)).
evidence(e_ksea(e3, s94, dec)).
evidence(p_fc(p0, s94, inc)).
evidence(p_fc(p1, s94, inc)).
evidence(p_fc(p2, s94, inc)).
evidence(p_fc(p3, s94, inc)).
evidence(p_fc(p4, s94, inc)).
evidence(p_fc(p5, s94, inc)).
evidence(p_fc(p6, s94, inc)).
evidence(p_fc(p7, s94, inc)).
evidence(p_fc(p8, s94, inc)).
evidence(p_fc(p9, s94, inc)).
--------------------
evidence(e_ksea(e1, s64, inc)).
evidence(e_ksea(e2, s64, inc)).
evidence(e_ksea(e3, s64, dec)).
evidence(p_fc(p0, s64, inc)).
evidence(p_fc(p1, s64, inc)).
evidence(p_fc(p2, s64, inc)).
evidence(p_fc(p3, s64, inc)).
evidence(p_fc(p4, s64, inc)).
evidence(p_fc(p5, s64, inc)).
evidence(p_fc(p6, s64, inc)).
evidence(p_fc(p7, s64, inc)).
evidence(p_fc(p8, s64, inc)).
evidence(p_fc(p9, s64, inc)).
--------------------
evidence(e_ksea(e1, s5, inc)).
evidence(e_ksea(e2, s5, inc)).
evidence(e_ksea(e3, s5, inc)).
evidence(p_fc(p0, s5, inc)).
evidence(p_fc(p1, s5, inc)).
evidence(p_fc(p2, s5, inc)).
evidence(p_fc(p3, s5, inc)).
evidence(p_fc(p4, s5, inc)).
evidence(p_fc(p5, s5, inc)).
evidence(p_fc(p6, s5, inc)).
evidence(p_fc(p7, s5, inc)).
evidence(p_fc(p8, s5, inc)).
evidence(p_fc(p9, s5, inc)).
--------------------
evidence(e_ksea(e1, s16, inc)).
evidence(e_ksea(e2, s16, inc)).
evidence(e_ksea(e3, s16, dec)).
evidence(p_fc(p0, s16, inc)).
evidence(p_fc(p1, s16, inc)).
evidence(p_fc(p2, s16, inc)).
evidence(p_fc(p3, s16, inc)).
evidence(p_fc(p4, s16, inc)).
evidence(p_fc(p5, s16, inc)).
evidence(p_fc(p6, s16, inc)).
evidence(p_fc(p7, s16, inc)).
evidence(p_fc(p8, s16, inc)).
evidence(p_fc(p9, s16, inc)).
--------------------
evidence(e_ksea(e1, s20, dec)).
evidence(e_ksea(e2, s20, inc)).
evidence(e_ksea(e3, s20, inc)).
evidence(p_fc(p0, s20, dec)).
evidence(p_fc(p1, s20, dec)).
evidence(p_fc(p2, s20, dec)).
evidence(p_fc(p3, s20, dec)).
evidence(p_fc(p4, s20, dec)).
evidence(p_fc(p5, s20, dec)).
evidence(p_fc(p6, s20, dec)).
evidence(p_fc(p7, s20, dec)).
evidence(p_fc(p8, s20, dec)).
evidence(p_fc(p9, s20, dec)).
--------------------
evidence(e_ksea(e1, s98, inc)).
evidence(e_ksea(e2, s98, inc)).
evidence(e_ksea(e3, s98, dec)).
evidence(p_fc(p0, s98, inc)).
evidence(p_fc(p1, s98, inc)).
evidence(p_fc(p2, s98, inc)).
evidence(p_fc(p3, s98, inc)).
evidence(p_fc(p4, s98, inc)).
evidence(p_fc(p5, s98, inc)).
evidence(p_fc(p6, s98, inc)).
evidence(p_fc(p7, s98, inc)).
evidence(p_fc(p8, s98, inc)).
evidence(p_fc(p9, s98, inc)).
--------------------
evidence(e_ksea(e1, s27, inc)).
evidence(e_ksea(e2, s27, dec)).
evidence(e_ksea(e3, s27, dec)).
evidence(p_fc(p0, s27, inc)).
evidence(p_fc(p1, s27, inc)).
evidence(p_fc(p2, s27, inc)).
evidence(p_fc(p3, s27, inc)).
evidence(p_fc(p4, s27, inc)).
evidence(p_fc(p5, s27, inc)).
evidence(p_fc(p6, s27, inc)).
evidence(p_fc(p7, s27, inc)).
evidence(p_fc(p8, s27, inc)).
evidence(p_fc(p9, s27, inc)).
--------------------
evidence(e_ksea(e1, s33, dec)).
evidence(e_ksea(e2, s33, inc)).
evidence(e_ksea(e3, s33, dec)).
evidence(p_fc(p0, s33, dec)).
evidence(p_fc(p1, s33, dec)).
evidence(p_fc(p2, s33, dec)).
evidence(p_fc(p3, s33, dec)).
evidence(p_fc(p4, s33, dec)).
evidence(p_fc(p5, s33, dec)).
evidence(p_fc(p6, s33, dec)).
evidence(p_fc(p7, s33, dec)).
evidence(p_fc(p8, s33, dec)).
evidence(p_fc(p9, s33, dec)).
--------------------
evidence(e_ksea(e1, s29, inc)).
evidence(e_ksea(e2, s29, dec)).
evidence(e_ksea(e3, s29, dec)).
evidence(p_fc(p0, s29, inc)).
evidence(p_fc(p1, s29, inc)).
evidence(p_fc(p2, s29, inc)).
evidence(p_fc(p3, s29, inc)).
evidence(p_fc(p4, s29, inc)).
evidence(p_fc(p5, s29, inc)).
evidence(p_fc(p6, s29, inc)).
evidence(p_fc(p7, s29, inc)).
evidence(p_fc(p8, s29, inc)).
evidence(p_fc(p9, s29, inc)).
--------------------
evidence(e_ksea(e1, s53, inc)).
evidence(e_ksea(e2, s53, dec)).
evidence(e_ksea(e3, s53, inc)).
evidence(p_fc(p0, s53, inc)).
evidence(p_fc(p1, s53, inc)).
evidence(p_fc(p2, s53, inc)).
evidence(p_fc(p3, s53, inc)).
evidence(p_fc(p4, s53, inc)).
evidence(p_fc(p5, s53, inc)).
evidence(p_fc(p6, s53, inc)).
evidence(p_fc(p7, s53, inc)).
evidence(p_fc(p8, s53, inc)).
evidence(p_fc(p9, s53, inc)).
--------------------
evidence(e_ksea(e1, s85, dec)).
evidence(e_ksea(e2, s85, dec)).
evidence(e_ksea(e3, s85, inc)).
evidence(p_fc(p0, s85, dec)).
evidence(p_fc(p1, s85, dec)).
evidence(p_fc(p2, s85, dec)).
evidence(p_fc(p3, s85, dec)).
evidence(p_fc(p4, s85, dec)).
evidence(p_fc(p5, s85, dec)).
evidence(p_fc(p6, s85, dec)).
evidence(p_fc(p7, s85, dec)).
evidence(p_fc(p8, s85, dec)).
evidence(p_fc(p9, s85, dec)).
--------------------
evidence(e_ksea(e1, s89, inc)).
evidence(e_ksea(e2, s89, inc)).
evidence(e_ksea(e3, s89, inc)).
evidence(p_fc(p0, s89, dec)).
evidence(p_fc(p1, s89, dec)).
evidence(p_fc(p2, s89, dec)).
evidence(p_fc(p3, s89, dec)).
evidence(p_fc(p4, s89, dec)).
evidence(p_fc(p5, s89, dec)).
evidence(p_fc(p6, s89, dec)).
evidence(p_fc(p7, s89, dec)).
evidence(p_fc(p8, s89, dec)).
evidence(p_fc(p9, s89, dec)).
--------------------
evidence(e_ksea(e1, s66, inc)).
evidence(e_ksea(e2, s66, dec)).
evidence(e_ksea(e3, s66, inc)).
evidence(p_fc(p0, s66, dec)).
evidence(p_fc(p1, s66, dec)).
evidence(p_fc(p2, s66, dec)).
evidence(p_fc(p3, s66, dec)).
evidence(p_fc(p4, s66, dec)).
evidence(p_fc(p5, s66, dec)).
evidence(p_fc(p6, s66, dec)).
evidence(p_fc(p7, s66, dec)).
evidence(p_fc(p8, s66, dec)).
evidence(p_fc(p9, s66, dec)).
--------------------
evidence(e_ksea(e1, s3, dec)).
evidence(e_ksea(e2, s3, dec)).
evidence(e_ksea(e3, s3, inc)).
evidence(p_fc(p0, s3, dec)).
evidence(p_fc(p1, s3, dec)).
evidence(p_fc(p2, s3, dec)).
evidence(p_fc(p3, s3, dec)).
evidence(p_fc(p4, s3, dec)).
evidence(p_fc(p5, s3, dec)).
evidence(p_fc(p6, s3, dec)).
evidence(p_fc(p7, s3, dec)).
evidence(p_fc(p8, s3, dec)).
evidence(p_fc(p9, s3, dec)).
--------------------
evidence(e_ksea(e1, s9, dec)).
evidence(e_ksea(e2, s9, inc)).
evidence(e_ksea(e3, s9, dec)).
evidence(p_fc(p0, s9, inc)).
evidence(p_fc(p1, s9, inc)).
evidence(p_fc(p2, s9, inc)).
evidence(p_fc(p3, s9, inc)).
evidence(p_fc(p4, s9, inc)).
evidence(p_fc(p5, s9, inc)).
evidence(p_fc(p6, s9, inc)).
evidence(p_fc(p7, s9, inc)).
evidence(p_fc(p8, s9, inc)).
evidence(p_fc(p9, s9, inc)).
--------------------
evidence(e_ksea(e1, s44, dec)).
evidence(e_ksea(e2, s44, dec)).
evidence(e_ksea(e3, s44, dec)).
evidence(p_fc(p0, s44, dec)).
evidence(p_fc(p1, s44, dec)).
evidence(p_fc(p2, s44, dec)).
evidence(p_fc(p3, s44, dec)).
evidence(p_fc(p4, s44, dec)).
evidence(p_fc(p5, s44, dec)).
evidence(p_fc(p6, s44, dec)).
evidence(p_fc(p7, s44, dec)).
evidence(p_fc(p8, s44, dec)).
evidence(p_fc(p9, s44, dec)).
--------------------
evidence(e_ksea(e1, s99, inc)).
evidence(e_ksea(e2, s99, inc)).
evidence(e_ksea(e3, s99, inc)).
evidence(p_fc(p0, s99, inc)).
evidence(p_fc(p1, s99, inc)).
evidence(p_fc(p2, s99, inc)).
evidence(p_fc(p3, s99, inc)).
evidence(p_fc(p4, s99, inc)).
evidence(p_fc(p5, s99, inc)).
evidence(p_fc(p6, s99, inc)).
evidence(p_fc(p7, s99, inc)).
evidence(p_fc(p8, s99, inc)).
evidence(p_fc(p9, s99, inc)).
--------------------
evidence(e_ksea(e1, s79, inc)).
evidence(e_ksea(e2, s79, inc)).
evidence(e_ksea(e3, s79, inc)).
evidence(p_fc(p0, s79, inc)).
evidence(p_fc(p1, s79, inc)).
evidence(p_fc(p2, s79, inc)).
evidence(p_fc(p3, s79, inc)).
evidence(p_fc(p4, s79, inc)).
evidence(p_fc(p5, s79, inc)).
evidence(p_fc(p6, s79, inc)).
evidence(p_fc(p7, s79, inc)).
evidence(p_fc(p8, s79, inc)).
evidence(p_fc(p9, s79, inc)).
--------------------
evidence(e_ksea(e1, s77, inc)).
evidence(e_ksea(e2, s77, inc)).
evidence(e_ksea(e3, s77, dec)).
evidence(p_fc(p0, s77, inc)).
evidence(p_fc(p1, s77, inc)).
evidence(p_fc(p2, s77, inc)).
evidence(p_fc(p3, s77, inc)).
evidence(p_fc(p4, s77, inc)).
evidence(p_fc(p5, s77, inc)).
evidence(p_fc(p6, s77, inc)).
evidence(p_fc(p7, s77, inc)).
evidence(p_fc(p8, s77, inc)).
evidence(p_fc(p9, s77, inc)).
--------------------
evidence(e_ksea(e1, s73, dec)).
evidence(e_ksea(e2, s73, dec)).
evidence(e_ksea(e3, s73, dec)).
evidence(p_fc(p0, s73, inc)).
evidence(p_fc(p1, s73, inc)).
evidence(p_fc(p2, s73, inc)).
evidence(p_fc(p3, s73, inc)).
evidence(p_fc(p4, s73, inc)).
evidence(p_fc(p5, s73, inc)).
evidence(p_fc(p6, s73, inc)).
evidence(p_fc(p7, s73, inc)).
evidence(p_fc(p8, s73, inc)).
evidence(p_fc(p9, s73, inc)).
--------------------
evidence(e_ksea(e1, s32, inc)).
evidence(e_ksea(e2, s32, inc)).
evidence(e_ksea(e3, s32, dec)).
evidence(p_fc(p0, s32, inc)).
evidence(p_fc(p1, s32, inc)).
evidence(p_fc(p2, s32, inc)).
evidence(p_fc(p3, s32, inc)).
evidence(p_fc(p4, s32, inc)).
evidence(p_fc(p5, s32, inc)).
evidence(p_fc(p6, s32, inc)).
evidence(p_fc(p7, s32, inc)).
evidence(p_fc(p8, s32, inc)).
evidence(p_fc(p9, s32, inc)).
--------------------
evidence(e_ksea(e1, s2, inc)).
evidence(e_ksea(e2, s2, dec)).
evidence(e_ksea(e3, s2, dec)).
evidence(p_fc(p0, s2, inc)).
evidence(p_fc(p1, s2, inc)).
evidence(p_fc(p2, s2, inc)).
evidence(p_fc(p3, s2, inc)).
evidence(p_fc(p4, s2, inc)).
evidence(p_fc(p5, s2, inc)).
evidence(p_fc(p6, s2, inc)).
evidence(p_fc(p7, s2, inc)).
evidence(p_fc(p8, s2, inc)).
evidence(p_fc(p9, s2, inc)).
--------------------
evidence(e_ksea(e1, s87, dec)).
evidence(e_ksea(e2, s87, inc)).
evidence(e_ksea(e3, s87, inc)).
evidence(p_fc(p0, s87, dec)).
evidence(p_fc(p1, s87, dec)).
evidence(p_fc(p2, s87, dec)).
evidence(p_fc(p3, s87, dec)).
evidence(p_fc(p4, s87, dec)).
evidence(p_fc(p5, s87, dec)).
evidence(p_fc(p6, s87, dec)).
evidence(p_fc(p7, s87, dec)).
evidence(p_fc(p8, s87, dec)).
evidence(p_fc(p9, s87, dec)).
--------------------
evidence(e_ksea(e1, s18, inc)).
evidence(e_ksea(e2, s18, inc)).
evidence(e_ksea(e3, s18, dec)).
evidence(p_fc(p0, s18, inc)).
evidence(p_fc(p1, s18, inc)).
evidence(p_fc(p2, s18, inc)).
evidence(p_fc(p3, s18, inc)).
evidence(p_fc(p4, s18, inc)).
evidence(p_fc(p5, s18, inc)).
evidence(p_fc(p6, s18, inc)).
evidence(p_fc(p7, s18, inc)).
evidence(p_fc(p8, s18, inc)).
evidence(p_fc(p9, s18, inc)).
--------------------
evidence(e_ksea(e1, s95, dec)).
evidence(e_ksea(e2, s95, inc)).
evidence(e_ksea(e3, s95, inc)).
evidence(p_fc(p0, s95, dec)).
evidence(p_fc(p1, s95, dec)).
evidence(p_fc(p2, s95, dec)).
evidence(p_fc(p3, s95, dec)).
evidence(p_fc(p4, s95, dec)).
evidence(p_fc(p5, s95, dec)).
evidence(p_fc(p6, s95, dec)).
evidence(p_fc(p7, s95, dec)).
evidence(p_fc(p8, s95, dec)).
evidence(p_fc(p9, s95, dec)).
--------------------
evidence(e_ksea(e1, s31, inc)).
evidence(e_ksea(e2, s31, inc)).
evidence(e_ksea(e3, s31, dec)).
evidence(p_fc(p0, s31, inc)).
evidence(p_fc(p1, s31, inc)).
evidence(p_fc(p2, s31, inc)).
evidence(p_fc(p3, s31, inc)).
evidence(p_fc(p4, s31, inc)).
evidence(p_fc(p5, s31, inc)).
evidence(p_fc(p6, s31, inc)).
evidence(p_fc(p7, s31, inc)).
evidence(p_fc(p8, s31, inc)).
evidence(p_fc(p9, s31, inc)).
--------------------
evidence(e_ksea(e1, s81, inc)).
evidence(e_ksea(e2, s81, inc)).
evidence(e_ksea(e3, s81, inc)).
evidence(p_fc(p0, s81, inc)).
evidence(p_fc(p1, s81, inc)).
evidence(p_fc(p2, s81, inc)).
evidence(p_fc(p3, s81, inc)).
evidence(p_fc(p4, s81, inc)).
evidence(p_fc(p5, s81, inc)).
evidence(p_fc(p6, s81, inc)).
evidence(p_fc(p7, s81, inc)).
evidence(p_fc(p8, s81, inc)).
evidence(p_fc(p9, s81, inc)).
--------------------
evidence(e_ksea(e1, s30, inc)).
evidence(e_ksea(e2, s30, dec)).
evidence(e_ksea(e3, s30, inc)).
evidence(p_fc(p0, s30, dec)).
evidence(p_fc(p1, s30, dec)).
evidence(p_fc(p2, s30, dec)).
evidence(p_fc(p3, s30, dec)).
evidence(p_fc(p4, s30, dec)).
evidence(p_fc(p5, s30, dec)).
evidence(p_fc(p6, s30, dec)).
evidence(p_fc(p7, s30, dec)).
evidence(p_fc(p8, s30, dec)).
evidence(p_fc(p9, s30, dec)).
--------------------
evidence(e_ksea(e1, s50, dec)).
evidence(e_ksea(e2, s50, inc)).
evidence(e_ksea(e3, s50, inc)).
evidence(p_fc(p0, s50, inc)).
evidence(p_fc(p1, s50, inc)).
evidence(p_fc(p2, s50, inc)).
evidence(p_fc(p3, s50, inc)).
evidence(p_fc(p4, s50, inc)).
evidence(p_fc(p5, s50, inc)).
evidence(p_fc(p6, s50, inc)).
evidence(p_fc(p7, s50, inc)).
evidence(p_fc(p8, s50, inc)).
evidence(p_fc(p9, s50, inc)).
--------------------
evidence(e_ksea(e1, s75, inc)).
evidence(e_ksea(e2, s75, inc)).
evidence(e_ksea(e3, s75, dec)).
evidence(p_fc(p0, s75, inc)).
evidence(p_fc(p1, s75, inc)).
evidence(p_fc(p2, s75, inc)).
evidence(p_fc(p3, s75, inc)).
evidence(p_fc(p4, s75, inc)).
evidence(p_fc(p5, s75, inc)).
evidence(p_fc(p6, s75, inc)).
evidence(p_fc(p7, s75, inc)).
evidence(p_fc(p8, s75, inc)).
evidence(p_fc(p9, s75, inc)).
--------------------
evidence(e_ksea(e1, s65, inc)).
evidence(e_ksea(e2, s65, dec)).
evidence(e_ksea(e3, s65, inc)).
evidence(p_fc(p0, s65, dec)).
evidence(p_fc(p1, s65, dec)).
evidence(p_fc(p2, s65, dec)).
evidence(p_fc(p3, s65, dec)).
evidence(p_fc(p4, s65, dec)).
evidence(p_fc(p5, s65, dec)).
evidence(p_fc(p6, s65, dec)).
evidence(p_fc(p7, s65, dec)).
evidence(p_fc(p8, s65, dec)).
evidence(p_fc(p9, s65, dec)).
--------------------
evidence(e_ksea(e1, s23, inc)).
evidence(e_ksea(e2, s23, dec)).
evidence(e_ksea(e3, s23, dec)).
evidence(p_fc(p0, s23, inc)).
evidence(p_fc(p1, s23, inc)).
evidence(p_fc(p2, s23, inc)).
evidence(p_fc(p3, s23, inc)).
evidence(p_fc(p4, s23, inc)).
evidence(p_fc(p5, s23, inc)).
evidence(p_fc(p6, s23, inc)).
evidence(p_fc(p7, s23, inc)).
evidence(p_fc(p8, s23, inc)).
evidence(p_fc(p9, s23, inc)).
--------------------
evidence(e_ksea(e1, s71, inc)).
evidence(e_ksea(e2, s71, inc)).
evidence(e_ksea(e3, s71, inc)).
evidence(p_fc(p0, s71, inc)).
evidence(p_fc(p1, s71, inc)).
evidence(p_fc(p2, s71, inc)).
evidence(p_fc(p3, s71, inc)).
evidence(p_fc(p4, s71, inc)).
evidence(p_fc(p5, s71, inc)).
evidence(p_fc(p6, s71, inc)).
evidence(p_fc(p7, s71, inc)).
evidence(p_fc(p8, s71, inc)).
evidence(p_fc(p9, s71, inc)).
--------------------
evidence(e_ksea(e1, s68, dec)).
evidence(e_ksea(e2, s68, inc)).
evidence(e_ksea(e3, s68, inc)).
evidence(p_fc(p0, s68, dec)).
evidence(p_fc(p1, s68, dec)).
evidence(p_fc(p2, s68, dec)).
evidence(p_fc(p3, s68, dec)).
evidence(p_fc(p4, s68, dec)).
evidence(p_fc(p5, s68, dec)).
evidence(p_fc(p6, s68, dec)).
evidence(p_fc(p7, s68, dec)).
evidence(p_fc(p8, s68, dec)).
evidence(p_fc(p9, s68, dec)).
--------------------
evidence(e_ksea(e1, s14, inc)).
evidence(e_ksea(e2, s14, inc)).
evidence(e_ksea(e3, s14, inc)).
evidence(p_fc(p0, s14, inc)).
evidence(p_fc(p1, s14, inc)).
evidence(p_fc(p2, s14, inc)).
evidence(p_fc(p3, s14, inc)).
evidence(p_fc(p4, s14, inc)).
evidence(p_fc(p5, s14, inc)).
evidence(p_fc(p6, s14, inc)).
evidence(p_fc(p7, s14, inc)).
evidence(p_fc(p8, s14, inc)).
evidence(p_fc(p9, s14, inc)).
--------------------
evidence(e_ksea(e1, s82, inc)).
evidence(e_ksea(e2, s82, inc)).
evidence(e_ksea(e3, s82, inc)).
evidence(p_fc(p0, s82, inc)).
evidence(p_fc(p1, s82, inc)).
evidence(p_fc(p2, s82, inc)).
evidence(p_fc(p3, s82, inc)).
evidence(p_fc(p4, s82, inc)).
evidence(p_fc(p5, s82, inc)).
evidence(p_fc(p6, s82, inc)).
evidence(p_fc(p7, s82, inc)).
evidence(p_fc(p8, s82, inc)).
evidence(p_fc(p9, s82, inc)).
--------------------
evidence(e_ksea(e1, s4, dec)).
evidence(e_ksea(e2, s4, inc)).
evidence(e_ksea(e3, s4, inc)).
evidence(p_fc(p0, s4, dec)).
evidence(p_fc(p1, s4, dec)).
evidence(p_fc(p2, s4, dec)).
evidence(p_fc(p3, s4, dec)).
evidence(p_fc(p4, s4, dec)).
evidence(p_fc(p5, s4, dec)).
evidence(p_fc(p6, s4, dec)).
evidence(p_fc(p7, s4, dec)).
evidence(p_fc(p8, s4, dec)).
evidence(p_fc(p9, s4, dec)).
--------------------
evidence(e_ksea(e1, s6, inc)).
evidence(e_ksea(e2, s6, inc)).
evidence(e_ksea(e3, s6, dec)).
evidence(p_fc(p0, s6, inc)).
evidence(p_fc(p1, s6, inc)).
evidence(p_fc(p2, s6, inc)).
evidence(p_fc(p3, s6, inc)).
evidence(p_fc(p4, s6, inc)).
evidence(p_fc(p5, s6, inc)).
evidence(p_fc(p6, s6, inc)).
evidence(p_fc(p7, s6, inc)).
evidence(p_fc(p8, s6, inc)).
evidence(p_fc(p9, s6, inc)).
--------------------
evidence(e_ksea(e1, s91, inc)).
evidence(e_ksea(e2, s91, dec)).
evidence(e_ksea(e3, s91, inc)).
evidence(p_fc(p0, s91, dec)).
evidence(p_fc(p1, s91, dec)).
evidence(p_fc(p2, s91, dec)).
evidence(p_fc(p3, s91, dec)).
evidence(p_fc(p4, s91, dec)).
evidence(p_fc(p5, s91, dec)).
evidence(p_fc(p6, s91, dec)).
evidence(p_fc(p7, s91, dec)).
evidence(p_fc(p8, s91, dec)).
evidence(p_fc(p9, s91, dec)).
--------------------
evidence(e_ksea(e1, s86, inc)).
evidence(e_ksea(e2, s86, inc)).
evidence(e_ksea(e3, s86, inc)).
evidence(p_fc(p0, s86, inc)).
evidence(p_fc(p1, s86, inc)).
evidence(p_fc(p2, s86, inc)).
evidence(p_fc(p3, s86, inc)).
evidence(p_fc(p4, s86, inc)).
evidence(p_fc(p5, s86, inc)).
evidence(p_fc(p6, s86, inc)).
evidence(p_fc(p7, s86, inc)).
evidence(p_fc(p8, s86, inc)).
evidence(p_fc(p9, s86, inc)).
--------------------
evidence(e_ksea(e1, s34, inc)).
evidence(e_ksea(e2, s34, dec)).
evidence(e_ksea(e3, s34, dec)).
evidence(p_fc(p0, s34, inc)).
evidence(p_fc(p1, s34, inc)).
evidence(p_fc(p2, s34, inc)).
evidence(p_fc(p3, s34, inc)).
evidence(p_fc(p4, s34, inc)).
evidence(p_fc(p5, s34, inc)).
evidence(p_fc(p6, s34, inc)).
evidence(p_fc(p7, s34, inc)).
evidence(p_fc(p8, s34, inc)).
evidence(p_fc(p9, s34, inc)).
--------------------
evidence(e_ksea(e1, s72, dec)).
evidence(e_ksea(e2, s72, dec)).
evidence(e_ksea(e3, s72, inc)).
evidence(p_fc(p0, s72, dec)).
evidence(p_fc(p1, s72, dec)).
evidence(p_fc(p2, s72, dec)).
evidence(p_fc(p3, s72, dec)).
evidence(p_fc(p4, s72, dec)).
evidence(p_fc(p5, s72, dec)).
evidence(p_fc(p6, s72, dec)).
evidence(p_fc(p7, s72, dec)).
evidence(p_fc(p8, s72, dec)).
evidence(p_fc(p9, s72, dec)).
--------------------
evidence(e_ksea(e1, s63, inc)).
evidence(e_ksea(e2, s63, inc)).
evidence(e_ksea(e3, s63, inc)).
evidence(p_fc(p0, s63, dec)).
evidence(p_fc(p1, s63, dec)).
evidence(p_fc(p2, s63, dec)).
evidence(p_fc(p3, s63, dec)).
evidence(p_fc(p4, s63, dec)).
evidence(p_fc(p5, s63, dec)).
evidence(p_fc(p6, s63, dec)).
evidence(p_fc(p7, s63, dec)).
evidence(p_fc(p8, s63, dec)).
evidence(p_fc(p9, s63, dec)).
--------------------
evidence(e_ksea(e1, s28, inc)).
evidence(e_ksea(e2, s28, dec)).
evidence(e_ksea(e3, s28, dec)).
evidence(p_fc(p0, s28, inc)).
evidence(p_fc(p1, s28, inc)).
evidence(p_fc(p2, s28, inc)).
evidence(p_fc(p3, s28, inc)).
evidence(p_fc(p4, s28, inc)).
evidence(p_fc(p5, s28, inc)).
evidence(p_fc(p6, s28, inc)).
evidence(p_fc(p7, s28, inc)).
evidence(p_fc(p8, s28, inc)).
evidence(p_fc(p9, s28, inc)).
--------------------
evidence(e_ksea(e1, s22, dec)).
evidence(e_ksea(e2, s22, dec)).
evidence(e_ksea(e3, s22, dec)).
evidence(p_fc(p0, s22, dec)).
evidence(p_fc(p1, s22, dec)).
evidence(p_fc(p2, s22, dec)).
evidence(p_fc(p3, s22, dec)).
evidence(p_fc(p4, s22, dec)).
evidence(p_fc(p5, s22, dec)).
evidence(p_fc(p6, s22, dec)).
evidence(p_fc(p7, s22, dec)).
evidence(p_fc(p8, s22, dec)).
evidence(p_fc(p9, s22, dec)).
--------------------
evidence(e_ksea(e1, s58, dec)).
evidence(e_ksea(e2, s58, inc)).
evidence(e_ksea(e3, s58, dec)).
evidence(p_fc(p0, s58, dec)).
evidence(p_fc(p1, s58, dec)).
evidence(p_fc(p2, s58, dec)).
evidence(p_fc(p3, s58, dec)).
evidence(p_fc(p4, s58, dec)).
evidence(p_fc(p5, s58, dec)).
evidence(p_fc(p6, s58, dec)).
evidence(p_fc(p7, s58, dec)).
evidence(p_fc(p8, s58, dec)).
evidence(p_fc(p9, s58, dec)).
--------------------
